#version 450 core
#pragma use_vulkan_memory_model
#extension GL_KHR_shader_subgroup_basic : enable
#extension GL_EXT_scalar_block_layout : enable
#extension GL_KHR_memory_scope_semantics : enable
#extension GL_KHR_cooperative_matrix : enable
#extension GL_EXT_shader_explicit_arithmetic_types_float16 : enable

layout(local_size_x = 32) in;

layout(set=0, binding=0) buffer Buf { float16_t data[]; } b;

void main() {
    coopmat<float16_t, gl_ScopeSubgroup, 16, 16, gl_MatrixUseA> matA;
    // 5 arguments with SSBO array
    coopMatLoad(matA, b.data, 0, 16, gl_CooperativeMatrixLayoutRowMajor);
}



